def tournaments_view():
    print("--------------")
    print("Que souhaitez-vous faire ?")
    print("")
    print("1/ Créer un nouveau tournoi")
    print("2/ Afficher la liste des tournois")
    print("3/ Modifier un tournoi")
    print("4/ Supprimer un tournoi")
    print("5/ Réinitialiser le programme")
    print("6/ Quitter")
